on: [push, workflow_dispatch]

env:
  TOOLS_URL: https://github.com/mmatyas/retropie-frontendchooser/releases/download/tools
  QT_VER: qt596
  TARGETS: "x11-static rpi1-static rpi2-static"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: APT deps
        run: sudo apt-get update && sudo apt-get install -y
          libgl-dev
          libudev-dev
          libx11-xcb-dev
          libxcb-glx0-dev
          libxi-dev
      - name: Get Qt
        working-directory: /tmp
        run: |
          for target in ${TARGETS}; do wget ${TOOLS_URL}/${QT_VER}_${target}.txz; done
          wget ${TOOLS_URL}/rpi-toolchain_483.txz
          wget ${TOOLS_URL}/rpi-sysroot_jessie_2017-07-05.txz
          for f in *.txz; do sudo tar xJf ${f} -C /opt/; done
          sudo ln -s ${QT_VER}_x11-static /opt/${QT_VER}_x11-static_hosttools
      - uses: actions/checkout@v2
      - name: Build
        run: for target in ${TARGETS}; do
          mkdir build_${target} && cd build_${target} &&
          /opt/${QT_VER}_${target}_hosttools/bin/qmake .. &&
          make install INSTALL_ROOT=$PWD/../install_${target} &&
          cd ..;
          done &&
          mkdir dist
      - name: Package
        working-directory: ./dist
        run: for target in ${TARGETS}; do
          zip -j retropie-frontendchooser_${target}.zip
            ../install_${target}/opt/retropie-frontendchooser/bin/retropie-frontendchooser;
          done
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: dist/*.zip
